# Generated by Django 5.1.1 on 2024-09-29 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(default='pending', max_length=10),
        ),
    ]
